# Generated by Django 5.0 on 2025-11-03 16:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Enable pgvector extension
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;'
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('movement', models.CharField(blank=True, max_length=100)),
                ('style_embedding', pgvector.django.VectorField(blank=True, dimensions=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_artist_name_43b0c8_idx'), models.Index(fields=['style'], name='core_artist_style_4c582c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='museums/logos/')),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('data_retention_days', models.IntegerField(default=90)),
                ('allow_visitor_feedback', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='core_museum_name_b2f7e6_idx'), models.Index(fields=['is_active'], name='core_museum_is_acti_e1eb90_idx')],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('year_created', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('installation', 'Installation'), ('digital', 'Digital Art'), ('mixed', 'Mixed Media'), ('other', 'Other')], max_length=20)),
                ('medium', models.CharField(blank=True, max_length=255)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('gallery_location', models.CharField(blank=True, max_length=255)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='artworks/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('video_360', models.FileField(blank=True, null=True, upload_to='artworks/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])])),
                ('audio_narration', models.FileField(blank=True, null=True, upload_to='artworks/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg'])])),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=512, null=True)),
                ('embedding_model', models.CharField(default='clip-ViT-B-32', max_length=50)),
                ('embedding_generated_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('historical_context', models.TextField(blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('scan_count', models.IntegerField(default=0)),
                ('avg_dwell_time_seconds', models.FloatField(default=0.0)),
                ('is_on_display', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='core.artist')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='core.museum')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuseumStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('curator', 'Curator'), ('staff', 'Staff Member')], default='staff', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='museum_staff', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='museum_staff', to='auth.permission', verbose_name='user permissions')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.museum')),
            ],
            options={
                'verbose_name': 'Museum Staff',
                'verbose_name_plural': 'Museum Staff',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('embedding_generation', 'Embedding Generation'), ('data_access', 'Data Access'), ('analytics_export', 'Analytics Export'), ('privacy_opt_out', 'Privacy Opt-Out'), ('error', 'System Error')], max_length=30)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['log_type', 'created_at'], name='core_system_log_typ_392524_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('analytics_consent', models.BooleanField(default=True)),
                ('opted_out', models.BooleanField(default=False)),
                ('artworks_scanned', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.museum')),
            ],
            options={
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='VisitorFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('love', '❤️ Love it'), ('like', '👍 Like it'), ('neutral', '😐 Neutral'), ('dislike', '👎 Dislike')], max_length=10)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.artwork')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.visitorsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('scan', 'Artwork Scan'), ('view_details', 'View Details'), ('play_audio', 'Play Audio Narration'), ('watch_video', 'Watch 360° Video'), ('view_related', 'View Related Artworks')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dwell_time_seconds', models.IntegerField(default=0)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.artwork')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.visitorsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CachedEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.VectorField(dimensions=512)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_embedding', to='core.artwork')),
            ],
            options={
                'ordering': ['-access_count'],
                'indexes': [models.Index(fields=['access_count'], name='core_cached_access__384d3f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['museum', 'is_on_display'], name='core_artwor_museum__e2c3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['artist'], name='core_artwor_artist__25d7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category'], name='core_artwor_categor_244400_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['title'], name='core_artwor_title_d219af_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['museum', 'session_start'], name='core_visito_museum__ee5544_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorsession',
            index=models.Index(fields=['session_start'], name='core_visito_session_4351c8_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorfeedback',
            index=models.Index(fields=['artwork', 'reaction'], name='core_visito_artwork_04846d_idx'),
        ),
        migrations.AddIndex(
            model_name='artworkinteraction',
            index=models.Index(fields=['session', 'timestamp'], name='core_artwor_session_55fd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='artworkinteraction',
            index=models.Index(fields=['artwork', 'interaction_type'], name='core_artwor_artwork_32f080_idx'),
        ),
        migrations.AddIndex(
            model_name='artworkinteraction',
            index=models.Index(fields=['timestamp'], name='core_artwor_timesta_403e94_idx'),
        ),
    ]
