# Generated by Django 5.0 on 2025-11-03 17:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='geofence_radius_meters',
            field=models.IntegerField(default=100, help_text='Radius in meters for geofencing'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/qrcodes/'),
        ),
        migrations.CreateModel(
            name='ArtworkTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('pt', 'Portuguese'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam')], max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('historical_context', models.TextField(blank=True)),
                ('audio_narration', models.FileField(blank=True, null=True, upload_to='artworks/audio/translations/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.artwork')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('artwork', 'language')},
            },
        ),
    ]
