# Generated by Django 5.0 on 2025-11-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artwork_geofence_radius_meters_artwork_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='qr_code',
        ),
    ]
